---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Install requirements
      delegate_to: localhost
      ansible.builtin.command: ansible-galaxy install -r roles/linux-desktop/requirements.yml
    # Other tasks that you run BEFORE the roles

  roles:
    - linux-base
    - linux-desktop

      #  - name: add ansible-pull cron job
      #cron:
      #name: ansible auto-provision
      #user: velociraptor
      #minute: "*/10"
    #job: ansible-pull -o -U https://github.com/librevlad/dotfiles.git
