---
- hosts: localhost
  connection: local
  become: true

  tasks:
  
- name: Configure server
  import_tasks: roles/linux-base/tasks/main.yml

        #  - name: add ansible-pull cron job
        #cron:
        #name: ansible auto-provision
        #user: velociraptor
        #minute: "*/10"
        #job: ansible-pull -o -U https://github.com/librevlad/dotfiles.git
