---
- name: Add ppa for i3-gaps
  ansible.builtin.apt_repository:
    repo: ppa:regolith-linux/release
    
- name: Add starws-box/deadbeef-player
  ansible.builtin.apt_repository:
    repo: ppa:starws-box/deadbeef-player
    
- name: Install Chrome
  include_role:
    name: darkwizard242.googlechrome
  
- name: wallpaper file
  copy:
    src: ../files/wallpaper.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root
    
- name: set wallpaper
  become_user: librevlad
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

- name: set wallpaper position
  become_user: librevlad
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
    
- name: install packages
  package:
    name:
      - i3-gaps 
      - i3lock 
      - terminator 
      - rofi 
      - vlc 
      - totem 
      - deadbeef 
      - rhythmbox 
      - kdenlive 
      - audacity 
      - telegram-desktop 
      - filezilla 
      - qbittorrent 
      - pavucontrol 
      - aircrack-ng 
      - reaver 
      - guvcview 
      - remmina 
      - x11vnc 
      - wine64 
      - playonlinux 
      - arc-theme 
      - lxappearance 
      - arandr 
      - ecryptfs-utils 
      - samba 
      - xclip 
      - xsel 
      - gparted 
      - kodi 
      - breeze 
      - breeze-gtk-theme 
      - breeze-icon-theme 
      - byobu speedtest-cli 
      - kodi-addons-dev shutter 
      - fonts-firacode 
      - pcmanfm 
      - feh 
      - scrot 
      - compton 
      - aircrack-ng 
      - reaver 
      - libreoffice 
      - blueman 
      - adb 
      - qemu-kvm 
      - davfs2 
      - gmtp 
      - pasystray 
      - i3-gaps
      - virtualbox
