---
- name: Install Chrome
  include_role:
    name: darkwizard242.googlechrome
  
- name: wallpaper file
  copy:
    src: ../files/wallpaper.png
    dest: /usr/share/backgrounds/ansible-wallpaper.png
    owner: root
    group: root
    
- name: set wallpaper
  become_user: librevlad
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file:///usr/share/backgrounds/ansible-wallpaper.png'"

- name: set wallpaper position
  become_user: librevlad
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
    
- name: install packages
  package:
    name:
      - i3lock 
      - terminator 
      - rofi 
      - vlc 
      - totem
      - rhythmbox 
      - kdenlive 
      - audacity 
      - filezilla 
      - qbittorrent 
      - pavucontrol 
      - aircrack-ng 
      - reaver 
      - guvcview 
      - remmina 
      - x11vnc 
      - wine64 
      - playonlinux 
      - arc-theme 
      - lxappearance 
      - arandr 
      - ecryptfs-utils 
      - samba 
      - xclip 
      - xsel 
      - gparted 
      - kodi
      - kodi-addons-dev 
      - breeze 
      - breeze-gtk-theme 
      - breeze-icon-theme 
      - fonts-firacode 
      - pcmanfm 
      - feh 
      - scrot 
      - compton 
      - aircrack-ng 
      - reaver 
      - libreoffice 
      - blueman 
      - adb 
      - qemu-kvm 
      - davfs2 
      - gmtp 
      - pasystray 
      - i3
      - virtualbox
      
 - name: Install snaps
  community.general.snap:
    name:
      - phpstorm
      - sublime-text
      - slack
      - opera
      - riseup-vpn
    options:
      - classic
